apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-frontend
                port:
                  number: 80
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user-frontend
                port:
                  number: 80
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: dashboard-frontend
                port:
                  number: 80
          - path: /notify
            pathType: Prefix
            backend:
              service:
                name: notification-frontend
                port:
                  number: 80
